create table if not exists public.dapp_api_keys (
  id bigint generated by default as identity primary key,
  dapp_id bigint not null references public.dapps(id) on delete cascade,
  key_prefix text not null,
  key_hash text not null,
  hash_algorithm text not null default 'scrypt',
  hash_version integer not null default 1,
  status text not null default 'active' check (status in ('active', 'revoked')),
  created_at timestamp with time zone not null default now(),
  rotated_at timestamp with time zone,
  last_used_at timestamp with time zone,
  revoked_at timestamp with time zone
);

create unique index if not exists dapp_api_keys_active_prefix_key
  on public.dapp_api_keys(key_prefix)
  where status = 'active';

create index if not exists dapp_api_keys_dapp_id_status_idx
  on public.dapp_api_keys(dapp_id, status);

insert into public.dapp_api_keys (
  dapp_id,
  key_prefix,
  key_hash,
  hash_algorithm,
  hash_version,
  status,
  created_at,
  rotated_at
)
select
  d.id,
  substring(d.apikey::text from 1 for 12),
  'sha256:v1:' || encode(extensions.digest(d.apikey::text, 'sha256'), 'hex'),
  'sha256',
  1,
  'active',
  coalesce(d.created_at, now()),
  now()
from public.dapps d
where d.apikey is not null
  and not exists (
    select 1
    from public.dapp_api_keys existing
    where existing.dapp_id = d.id
      and existing.status = 'active'
  );

alter table public.dapp_api_keys enable row level security;

grant select, insert, update, delete on table public.dapp_api_keys to service_role;
grant usage, select on sequence public.dapp_api_keys_id_seq to service_role;
