


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."delivery_status" AS ENUM (
    'pending',
    'succeeded',
    'failed'
);


ALTER TYPE "public"."delivery_status" OWNER TO "postgres";


CREATE TYPE "public"."error_category" AS ENUM (
    'network_error',
    'client_error',
    'server_error'
);


ALTER TYPE "public"."error_category" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."assign_secret_number"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    -- Select the count of secrets for the user and assign the next sequential number
    NEW.secret_sequential_id := (
        SELECT COALESCE(MAX(secret_sequential_id), 0) + 1
        FROM dapp_user_secrets
        WHERE dapp_user_uuid = NEW.dapp_user_uuid
    );
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."assign_secret_number"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."create_user_check_family"("p_uniquevalue" "text", "p_stamptype" smallint, "p_dapp_id" bigint) RETURNS TABLE("user_id" bigint, "dapp_id" bigint, "created_at" timestamp with time zone, "master_auth_uniquevalue" "text", "uuid" "uuid", "is_authorized" boolean)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    WITH user_data AS (
        SELECT u.id AS user_id, s.uniquevalue, s.stamptype, u.parent
        FROM public.stamps s
        JOIN public.users u ON s.created_by_user_id = u.id
        WHERE s.uniquevalue = p_uniquevalue AND s.stamptype = p_stamptype
    ),
    parent_users AS (
        SELECT DISTINCT u.id AS parent_user_id, ud.uniquevalue, ud.stamptype
        FROM user_data ud
        JOIN public.users u ON ud.parent = u.id
    ),
    sibling_users AS (
        SELECT DISTINCT u.id AS sibling_user_id, ud.uniquevalue, ud.stamptype
        FROM user_data ud
        JOIN public.users u ON ud.parent = u.parent
        WHERE u.id <> ud.user_id
    ),
    children_users AS (
        SELECT DISTINCT u.id AS child_user_id, ud.uniquevalue, ud.stamptype
        FROM user_data ud
        JOIN public.users u ON u.parent = ud.user_id
    ),
    all_users AS (
        SELECT user_id, uniquevalue, stamptype FROM user_data
        UNION
        SELECT parent_user_id AS user_id, uniquevalue, stamptype FROM parent_users
        UNION
        SELECT sibling_user_id AS user_id, uniquevalue, stamptype FROM sibling_users
        UNION
        SELECT child_user_id AS user_id, uniquevalue, stamptype FROM children_users
    )
    SELECT DISTINCT au.user_id, du.dapp_id, du.created_at, du.master_auth_uniquevalue, du.uuid, du.is_authorized
    FROM all_users au
    LEFT JOIN public.dapp_users du ON au.user_id = du.user_id AND du.dapp_id = p_dapp_id;
END;
$$;


ALTER FUNCTION "public"."create_user_check_family"("p_uniquevalue" "text", "p_stamptype" smallint, "p_dapp_id" bigint) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."dapp-admin-users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "uid" "uuid" DEFAULT "gen_random_uuid"(),
    "dapp_id" bigint,
    "dappuser_uuid" "uuid"
);


ALTER TABLE "public"."dapp-admin-users" OWNER TO "postgres";


ALTER TABLE "public"."dapp-admin-users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admin-users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_users" (
    "id" bigint NOT NULL,
    "dapp_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "is_authorized" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "modified_at" timestamp with time zone,
    "username" "text",
    "user_data" "jsonb",
    "master_auth_uniquevalue" "text",
    "auth_stamp" bigint
);


ALTER TABLE "public"."dapp_users" OWNER TO "postgres";


COMMENT ON TABLE "public"."dapp_users" IS 'A user authorizes dApps by creating a record in this table for each dApp that can access their data. Only one record allowed per user per app. Table "stamp_dappuser_permissions" references this table.';



COMMENT ON COLUMN "public"."dapp_users"."username" IS 'Each user can have a username that''s unique to the dapp';



COMMENT ON COLUMN "public"."dapp_users"."user_data" IS 'JSON to hold various info related to the user';



COMMENT ON COLUMN "public"."dapp_users"."master_auth_uniquevalue" IS 'In case of Sybil attack, if this dAppuser is not master, then this is a link to the stamp used to authenticate the master-dapp-user.';



COMMENT ON COLUMN "public"."dapp_users"."auth_stamp" IS 'Link to the stamp that was used by create-user to create the dapp-user in the first place';



CREATE TABLE IF NOT EXISTS "public"."stamps" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by_user_id" bigint NOT NULL,
    "unique_hash" "text",
    "created_by_app" bigint NOT NULL,
    "stamptype" smallint NOT NULL,
    "uniquevalue" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "stamp_json" "jsonb",
    "type_and_uniquehash" "text" NOT NULL,
    "parent_stamp" bigint,
    "user_id_and_uniqueval" "text",
    "is_valid" boolean DEFAULT true NOT NULL,
    "identity" "text",
    "rawscore" numeric,
    "is_third_party" boolean,
    "is_auth" boolean
);


ALTER TABLE "public"."stamps" OWNER TO "postgres";


COMMENT ON TABLE "public"."stamps" IS 'Stamps can be related to accounts, social media, KYC, uniqueness protocols, or PII such as email or phone number';



COMMENT ON COLUMN "public"."stamps"."created_by_app" IS 'Which app did the user use when creating the stamp. ';



COMMENT ON COLUMN "public"."stamps"."stamptype" IS 'Every stamp must have a type from the stamptypes table';



COMMENT ON COLUMN "public"."stamps"."uniquevalue" IS 'The unique identifier related to each stamp (like @kaz for Telegram)';



COMMENT ON COLUMN "public"."stamps"."stamp_json" IS 'JSON with the full collection of data related to the stamp';



COMMENT ON COLUMN "public"."stamps"."type_and_uniquehash" IS 'Concatenation of the stamptype and the uniquehash';



COMMENT ON COLUMN "public"."stamps"."parent_stamp" IS 'If the creation of one stamp (e.g. Discord sub) results in others being created too (e.g. email, phone), then these are child stamps of the "Discord sub" parent';



COMMENT ON COLUMN "public"."stamps"."rawscore" IS 'Holds the value imported from GitCoinPassport. Also holds a score representing the strength of a WorldCoin ID, etc.';



COMMENT ON COLUMN "public"."stamps"."is_third_party" IS 'Stamps created by create-user are set to FALSE';



COMMENT ON COLUMN "public"."stamps"."is_auth" IS 'Set to TRUE if the stamp is used to authenticate a cubid-user.';



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "email" "text",
    "address" json,
    "user_info" "jsonb",
    "profession" "text",
    "employer" "text",
    "poh_IsRegistered" boolean,
    "is_master" boolean,
    "created_by_app" bigint,
    "is_dupe" boolean,
    "is_3rd_party" boolean,
    "parent" bigint,
    "modified_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "dao_info" "jsonb",
    "username" "text",
    "profile_pic" "text",
    "is_human" boolean DEFAULT true NOT NULL,
    "phone" "text",
    "cubid_country" "text",
    "cubid_postalcode" "text",
    "unique_phone" "text",
    "evm" "text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON COLUMN "public"."users"."parent" IS 'User records can have parent-child relationships. Typically a record created by a third party app would later be assigned as a child of a user record which was created in a Cubid-native app.';



COMMENT ON COLUMN "public"."users"."is_human" IS 'TRUE for individual humans, FALSE for organisations, DAOs, collectives, corporations, groups, etc.';



CREATE OR REPLACE VIEW "public"."all_blacklisted_stamps_hashed" AS
 SELECT "du"."dapp_id",
    "s"."stamptype",
    "s"."unique_hash"
   FROM (("public"."stamps" "s"
     JOIN "public"."dapp_users" "du" ON (("s"."created_by_user_id" = "du"."user_id")))
     JOIN "public"."users" "u" ON (("du"."user_id" = "u"."id")))
  WHERE ("u"."is_human" = true)
  GROUP BY "s"."stamptype", "s"."unique_hash", "du"."dapp_id"
 HAVING ("count"(DISTINCT "du"."id") > 1);


ALTER VIEW "public"."all_blacklisted_stamps_hashed" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_blacklisted_stamps_raw" AS
 SELECT "du"."dapp_id",
    "s"."stamptype",
    "s"."uniquevalue"
   FROM (("public"."stamps" "s"
     JOIN "public"."dapp_users" "du" ON (("s"."created_by_user_id" = "du"."user_id")))
     JOIN "public"."users" "u" ON (("du"."user_id" = "u"."id")))
  WHERE ("u"."is_human" = true)
  GROUP BY "s"."stamptype", "s"."uniquevalue", "du"."dapp_id"
 HAVING ("count"(DISTINCT "du"."id") > 1);


ALTER VIEW "public"."all_blacklisted_stamps_raw" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stamp_dappuser_permissions" (
    "dappuser_id" "uuid" NOT NULL,
    "stamp_id" bigint NOT NULL,
    "can_read" boolean DEFAULT true NOT NULL,
    "can_write" boolean DEFAULT false NOT NULL,
    "can_delete" boolean DEFAULT false NOT NULL,
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."stamp_dappuser_permissions" OWNER TO "postgres";


COMMENT ON TABLE "public"."stamp_dappuser_permissions" IS 'Each stamp need to be permissioned uniquely for each combination of dApp and User.';



CREATE TABLE IF NOT EXISTS "public"."stampscore_dapps" (
    "API_key" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "dapp_id" bigint NOT NULL,
    "schema_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."stampscore_dapps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stampscores_available" (
    "id" bigint NOT NULL,
    "schema_id" bigint,
    "stamptype_id" smallint,
    "is_simple_stamp" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text",
    "criteria" "text",
    "is_GP_replacement" boolean,
    "score" real,
    "GP_equivalent" "text"
);


ALTER TABLE "public"."stampscores_available" OWNER TO "postgres";


COMMENT ON TABLE "public"."stampscores_available" IS 'Each scoring schema will have a set of multiple scores available to it. Some scores just require the presence of the corresponding stamp, while other have more complex criteria.';



COMMENT ON COLUMN "public"."stampscores_available"."is_GP_replacement" IS 'True if this stamp is also available in Gitcoin Passport';



CREATE OR REPLACE VIEW "public"."all_dappusers_w_stamps" AS
 SELECT "p"."dappuser_id",
    "p"."stamp_id",
    "s"."stamptype",
    "s"."is_valid" AS "is_valid_stamp",
    "sa"."score" AS "stamp_score"
   FROM (((("public"."stamp_dappuser_permissions" "p"
     LEFT JOIN "public"."dapp_users" "du" ON ((("p"."dappuser_id")::"text" = ("du"."uuid")::"text")))
     LEFT JOIN "public"."stamps" "s" ON (("p"."stamp_id" = "s"."id")))
     LEFT JOIN "public"."stampscore_dapps" "sd" ON (("du"."dapp_id" = "sd"."dapp_id")))
     LEFT JOIN "public"."stampscores_available" "sa" ON ((("sd"."schema_id" = "sa"."schema_id") AND ("s"."stamptype" = "sa"."stamptype_id"))))
  WHERE (("p"."can_read" = true) AND ("du"."is_authorized" = true) AND ("s"."is_valid" = true));


ALTER VIEW "public"."all_dappusers_w_stamps" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_dappusers_w_user" AS
 SELECT "du"."dapp_id",
    "du"."user_id",
    "du"."username",
    "du"."user_data" AS "dappuser_info",
    "u"."user_info"
   FROM ("public"."dapp_users" "du"
     LEFT JOIN "public"."users" "u" ON (("du"."user_id" = "u"."id")))
  WHERE ("du"."is_authorized" = true);


ALTER VIEW "public"."all_dappusers_w_user" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_users_and_parents" AS
 SELECT "id",
    COALESCE("parent", "id") AS "parent_id"
   FROM "public"."users";


ALTER VIEW "public"."all_users_and_parents" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_duplicate_stamps" AS
 SELECT "s"."type_and_uniquehash",
    "s"."uniquevalue",
    "array_agg"(DISTINCT "s"."created_by_user_id") AS "user_ids",
    "count"(DISTINCT "up"."parent_id") AS "parent_count",
    "array_agg"(DISTINCT "s"."id") AS "stamp_ids",
    "count"(DISTINCT "s"."created_by_user_id") AS "user_count",
    "array_agg"(DISTINCT "up"."parent_id") AS "parent_user_ids",
    "count"(DISTINCT "s"."id") AS "stamp_count"
   FROM ("public"."stamps" "s"
     JOIN "public"."all_users_and_parents" "up" ON (("s"."created_by_user_id" = "up"."id")))
  GROUP BY "s"."type_and_uniquehash", "s"."uniquevalue"
 HAVING (("count"(DISTINCT "s"."created_by_user_id") > 1) OR ("count"(DISTINCT "s"."id") > 1));


ALTER VIEW "public"."all_duplicate_stamps" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_greylisted_stamps" AS
 SELECT "type_and_uniquehash",
    "user_ids",
    "parent_user_ids",
    "stamp_ids"
   FROM "public"."all_duplicate_stamps" "ds"
  WHERE ("parent_count" > 1);


ALTER VIEW "public"."all_greylisted_stamps" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_greylisted_stamps_raw" AS
 SELECT "s"."type_and_uniquehash"
   FROM ("public"."stamps" "s"
     JOIN ( SELECT "users"."id",
            COALESCE("users"."parent", "users"."id") AS "parent_id"
           FROM "public"."users") "up" ON (("s"."created_by_user_id" = "up"."id")))
  GROUP BY "s"."type_and_uniquehash"
 HAVING ("count"(DISTINCT "up"."parent_id") > 1);


ALTER VIEW "public"."all_greylisted_stamps_raw" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_stamp_identities" AS
 SELECT DISTINCT ON ("s"."uniquevalue") "s"."uniquevalue",
    "s"."stamptype",
    "u"."id" AS "user_id",
    "du"."dapp_id",
    "du"."uuid" AS "app_scoped_uuid",
    "du"."is_authorized"
   FROM (("public"."stamps" "s"
     JOIN "public"."users" "u" ON (("s"."created_by_user_id" = "u"."id")))
     JOIN "public"."dapp_users" "du" ON (("u"."id" = "du"."user_id")))
  WHERE ("s"."stamptype" = 13);


ALTER VIEW "public"."all_stamp_identities" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_whitelisted_stamps" AS
 SELECT "s"."type_and_uniquehash",
    "array_agg"("s"."id") AS "stanp_ids",
    "count"("s"."id") AS "stamp_count",
    "array_agg"("s"."created_by_user_id") AS "user_ids",
    "count"("s"."created_by_user_id") AS "user_count",
    "count"(DISTINCT "s"."created_by_user_id") AS "user_count_distinct",
    "count"(DISTINCT "up"."parent_id") AS "parent_count_distinct"
   FROM (("public"."stamps" "s"
     LEFT JOIN "public"."all_greylisted_stamps" "g" ON (("s"."type_and_uniquehash" = "g"."type_and_uniquehash")))
     LEFT JOIN "public"."all_users_and_parents" "up" ON (("s"."created_by_user_id" = "up"."id")))
  WHERE ("g"."type_and_uniquehash" IS NULL)
  GROUP BY "s"."type_and_uniquehash";


ALTER VIEW "public"."all_whitelisted_stamps" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_unique_stamps" AS
 SELECT "s"."type_and_uniquehash",
        CASE
            WHEN ("g"."type_and_uniquehash" IS NOT NULL) THEN 'Blacklisted'::"text"
            WHEN ("w"."type_and_uniquehash" IS NOT NULL) THEN 'Whitelisted'::"text"
            ELSE 'Undefined'::"text"
        END AS "status"
   FROM ((( SELECT DISTINCT "stamps"."type_and_uniquehash"
           FROM "public"."stamps") "s"
     LEFT JOIN "public"."all_greylisted_stamps" "g" ON (("s"."type_and_uniquehash" = "g"."type_and_uniquehash")))
     LEFT JOIN "public"."all_whitelisted_stamps" "w" ON (("s"."type_and_uniquehash" = "w"."type_and_uniquehash")))
  ORDER BY "s"."type_and_uniquehash";


ALTER VIEW "public"."all_unique_stamps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dapps" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "appname" "text",
    "url" "text",
    "uid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "apikey" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "admin_uid" "text",
    "is_cubid_native" boolean DEFAULT false,
    "redirect_url" "text"
);


ALTER TABLE "public"."dapps" OWNER TO "postgres";


COMMENT ON COLUMN "public"."dapps"."is_cubid_native" IS 'True for apps that we develop and own, with native access to our auth and db';



CREATE TABLE IF NOT EXISTS "public"."stamptypes" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "stamptype" "text",
    "stampcategory" "text",
    "validationschema" json,
    "short_description" "text",
    "Notes" "text",
    "salt" "text" NOT NULL,
    "allow_multiple_per_user" boolean DEFAULT true NOT NULL,
    "restrict_dupes_globally" boolean DEFAULT false NOT NULL,
    "stamp_score" bigint DEFAULT '1'::bigint,
    "is_auth_enabled" boolean DEFAULT false NOT NULL,
    "show_in_admin_console" boolean DEFAULT true,
    "is_score_enabled" boolean DEFAULT true,
    "validation_regex" "text",
    "v2stamptype" "text",
    "format" "text",
    "example" "text",
    "example_chains" "text",
    "highlevel" "text",
    "fields_to_use" "jsonb",
    "is_app_scoped" boolean,
    "validation_method" "text",
    "is_in_blacklist" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."stamptypes" OWNER TO "postgres";


COMMENT ON COLUMN "public"."stamptypes"."Notes" IS 'Note to devs';



COMMENT ON COLUMN "public"."stamptypes"."salt" IS 'Unique salt for each stamptype';



COMMENT ON COLUMN "public"."stamptypes"."allow_multiple_per_user" IS 'BOOL. True if one user is allowed to have more than one (e.g. emails, wallets). False for stamps that can only be one stamp per user (e.g. Idena, BrightID)';



COMMENT ON COLUMN "public"."stamptypes"."restrict_dupes_globally" IS 'If a phone or email is entered previously, we won''t ever allow a new user to enter the same. This field isn''t used yet, it''s an idea on what''s required in order for ';



COMMENT ON COLUMN "public"."stamptypes"."stamp_score" IS 'Deprecated column, replaced with dapps_stampscore table';



COMMENT ON COLUMN "public"."stamptypes"."is_auth_enabled" IS 'Some stamp types are enabled for user authentication, for example email, phone and WalletConnect';



COMMENT ON COLUMN "public"."stamptypes"."is_score_enabled" IS 'Tells admin console which types to allow "include in score"';



COMMENT ON COLUMN "public"."stamptypes"."is_app_scoped" IS 'True if the Oauth provider send us an app-scoped UID';



COMMENT ON COLUMN "public"."stamptypes"."is_in_blacklist" IS 'Stamptypes that are not unique to a user should not be blacklisted';



CREATE OR REPLACE VIEW "public"."all_stamps" AS
 SELECT "t"."stampcategory",
    "t"."short_description" AS "short_desctiption",
    "s"."uniquevalue",
    "us"."status",
    "s"."stamp_json",
    "s"."created_by_app",
    "a"."appname",
    "s"."created_at",
    "u"."email",
    "s"."id",
    "s"."identity"
   FROM (((("public"."stamps" "s"
     LEFT JOIN "public"."stamptypes" "t" ON (("s"."stamptype" = "t"."id")))
     LEFT JOIN "public"."all_unique_stamps" "us" ON (("s"."type_and_uniquehash" = "us"."type_and_uniquehash")))
     LEFT JOIN "public"."dapps" "a" ON (("s"."created_by_app" = "a"."id")))
     LEFT JOIN "public"."users" "u" ON (("s"."created_by_user_id" = "u"."id")));


ALTER VIEW "public"."all_stamps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stampscore_schemas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text",
    "human_threshold" real DEFAULT '20'::real
);


ALTER TABLE "public"."stampscore_schemas" OWNER TO "postgres";


COMMENT ON TABLE "public"."stampscore_schemas" IS 'Each scorer will have it''s own schema, which can be accessed using a dedicated API key';



COMMENT ON COLUMN "public"."stampscore_schemas"."human_threshold" IS 'The score required at minimum to be considered a human';



CREATE OR REPLACE VIEW "public"."all_stampscores_available_extended" AS
 SELECT "sss"."description" AS "schema_description",
    "st"."stampcategory",
    "st"."stamptype",
    "ssa"."description",
    "ssa"."is_simple_stamp",
    "ssa"."criteria",
    "ssa"."is_GP_replacement",
    "ssa"."score",
    "ssa"."GP_equivalent",
    "ssa"."created_at",
    "ssa"."id" AS "available_id",
    "ssa"."stamptype_id",
    "sss"."human_threshold",
    "ssa"."schema_id"
   FROM (("public"."stampscores_available" "ssa"
     LEFT JOIN "public"."stampscore_schemas" "sss" ON (("ssa"."schema_id" = "sss"."id")))
     LEFT JOIN "public"."stamptypes" "st" ON (("ssa"."stamptype_id" = "st"."id")));


ALTER VIEW "public"."all_stampscores_available_extended" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_unique_stamps_detailed" AS
 SELECT "s"."type_and_uniquehash",
        CASE
            WHEN ("g"."type_and_uniquehash" IS NOT NULL) THEN 'Blacklisted'::"text"
            WHEN ("w"."type_and_uniquehash" IS NOT NULL) THEN 'Whitelisted'::"text"
            ELSE 'Undefined'::"text"
        END AS "status",
    "array_agg"("s"."id") AS "stanp_ids",
    "count"("s"."id") AS "stamp_count",
    "array_agg"(DISTINCT "s"."created_by_user_id") AS "user_ids",
    "count"(DISTINCT "s"."created_by_user_id") AS "user_count_distinct",
    "count"(DISTINCT "up"."parent_id") AS "parent_count_distinct",
    "array_agg"(DISTINCT "s"."uniquevalue") AS "uniquevalues"
   FROM ((("public"."stamps" "s"
     LEFT JOIN "public"."all_greylisted_stamps" "g" ON (("s"."type_and_uniquehash" = "g"."type_and_uniquehash")))
     LEFT JOIN "public"."all_whitelisted_stamps" "w" ON (("s"."type_and_uniquehash" = "w"."type_and_uniquehash")))
     LEFT JOIN "public"."all_users_and_parents" "up" ON (("s"."created_by_user_id" = "up"."id")))
  GROUP BY "s"."type_and_uniquehash",
        CASE
            WHEN ("g"."type_and_uniquehash" IS NOT NULL) THEN 'Blacklisted'::"text"
            WHEN ("w"."type_and_uniquehash" IS NOT NULL) THEN 'Whitelisted'::"text"
            ELSE 'Undefined'::"text"
        END
  ORDER BY "s"."type_and_uniquehash";


ALTER VIEW "public"."all_unique_stamps_detailed" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."all_unique_stamps_expanded" AS
 SELECT "s"."type_and_uniquehash",
    "array_agg"(DISTINCT "us"."status") AS "blacklisted",
    "array_agg"(DISTINCT "s"."id") AS "stanp_ids_distinct",
    "array_agg"(DISTINCT "s"."created_by_user_id") AS "user_ids_distinct",
    "array_agg"(DISTINCT "u"."email") AS "user_emails",
    "array_agg"(DISTINCT "s"."created_by_app") AS "app_ids_distinct",
    "array_agg"(DISTINCT "s"."stamptype") AS "stamptype",
    "array_agg"(DISTINCT "s"."uniquevalue") AS "uniquevalue",
    "array_agg"(DISTINCT "s"."stamp_json") AS "stamp_json"
   FROM (("public"."stamps" "s"
     JOIN "public"."all_unique_stamps" "us" ON (("s"."type_and_uniquehash" = "us"."type_and_uniquehash")))
     LEFT JOIN "public"."users" "u" ON (("s"."created_by_user_id" = "u"."id")))
  GROUP BY "s"."type_and_uniquehash";


ALTER VIEW "public"."all_unique_stamps_expanded" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."authorized_dapps_deprecated" (
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "dapp_id" bigint NOT NULL,
    "stamp_id" bigint NOT NULL,
    "dapp_and_stamp_id" "text",
    "can_read" boolean DEFAULT true NOT NULL,
    "can_update" boolean DEFAULT true NOT NULL,
    "can_delete" boolean DEFAULT true NOT NULL,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text")
);


ALTER TABLE "public"."authorized_dapps_deprecated" OWNER TO "postgres";


COMMENT ON TABLE "public"."authorized_dapps_deprecated" IS 'Deprecated, replaced by stamp_dappuser_permissions.';



CREATE TABLE IF NOT EXISTS "public"."blacklist_deprecated" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "identifier" "text"
);


ALTER TABLE "public"."blacklist_deprecated" OWNER TO "postgres";


ALTER TABLE "public"."blacklist_deprecated" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."blacklist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."brightid-data" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "explorer-id" "text",
    "name" "text",
    "status" "text",
    "level" "text",
    "incoming-level" "text",
    "image" "text",
    "email" "text",
    "connected-to" "text",
    "both-id" "text"
);


ALTER TABLE "public"."brightid-data" OWNER TO "postgres";


ALTER TABLE "public"."brightid-data" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."brightid-data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."connections" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "target_user_id" bigint,
    "created_by_user_id" bigint,
    "trustlevel" integer
);


ALTER TABLE "public"."connections" OWNER TO "postgres";


ALTER TABLE "public"."connections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."connections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cron_logs" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"(),
    "status" "text",
    "note" "text"
);


ALTER TABLE "public"."cron_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cronjobs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "modified_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "target_chain" bigint NOT NULL,
    "target_account" "text" NOT NULL,
    "source_account" "text" NOT NULL,
    "cronjob_type" "text" NOT NULL,
    "user_id" bigint NOT NULL,
    "source_chain" "text" NOT NULL,
    "latest_value" "jsonb",
    "status" "text" DEFAULT 'new'::"text" NOT NULL,
    "class" bigint NOT NULL,
    "token" bigint NOT NULL
);


ALTER TABLE "public"."cronjobs" OWNER TO "postgres";


COMMENT ON TABLE "public"."cronjobs" IS 'When a user mints for example Gitcoin Passport scores to a chain it''s logged here, which a daily cron job monitors for updates to the score';



COMMENT ON COLUMN "public"."cronjobs"."cronjob_type" IS 'Describes what we are minting and updating. "gp-score" is the default score provided from GP, "gp-stamps" provides the json with all the stamps of the user from GP. The corresponding values for our native stamp info is "cubid-score" and "cubid-stamps"';



COMMENT ON COLUMN "public"."cronjobs"."source_chain" IS 'Chain of the source data, e.g. "Ethereum" for Gitcoin Passport';



COMMENT ON COLUMN "public"."cronjobs"."latest_value" IS 'The most recent known value, which also is the value of the SBT on chain';



COMMENT ON COLUMN "public"."cronjobs"."status" IS 'Options include "new", "running", "error running" and "expired"';



COMMENT ON COLUMN "public"."cronjobs"."class" IS 'The SBT class';



COMMENT ON COLUMN "public"."cronjobs"."token" IS 'The ID of the token to be updated';



ALTER TABLE "public"."dapps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cubid-superapps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_pages" (
    "id" bigint NOT NULL,
    "dapp_id" bigint NOT NULL,
    "page_name" "text" DEFAULT 'default'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "redirect_url" "text",
    "template" "text" DEFAULT 'alllowpage'::"text",
    "greeting" "text"
);


ALTER TABLE "public"."dapp_pages" OWNER TO "postgres";


COMMENT ON TABLE "public"."dapp_pages" IS 'One line item for each Allow-page';



ALTER TABLE "public"."dapp_pages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_pages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_stampscores_deprecated" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "stamptype_id" smallint,
    "score" real,
    "description" "text",
    "criteria" "text",
    "dapp_id" bigint
);


ALTER TABLE "public"."dapp_stampscores_deprecated" OWNER TO "postgres";


COMMENT ON TABLE "public"."dapp_stampscores_deprecated" IS 'Each dapp might have it''s own stamptypes with its own custom scoring';



ALTER TABLE "public"."dapp_stampscores_deprecated" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_stampscores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_stamptypes" (
    "dapp_id" bigint NOT NULL,
    "stamptype_id" smallint NOT NULL,
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_auth_enabled" boolean NOT NULL,
    "include_in_score" boolean DEFAULT true,
    "is_infosharing_required" boolean DEFAULT false NOT NULL,
    "info_sharing_type_id" bigint NOT NULL,
    "page_id" bigint NOT NULL
);


ALTER TABLE "public"."dapp_stamptypes" OWNER TO "postgres";


COMMENT ON TABLE "public"."dapp_stamptypes" IS 'The Amin(s) of each dApp can choose which stamptypes they want as mandatory or optional in their dApp';



COMMENT ON COLUMN "public"."dapp_stamptypes"."is_auth_enabled" IS 'Controls which stamptypes are allowed for authentication';



COMMENT ON COLUMN "public"."dapp_stamptypes"."include_in_score" IS 'Set to true if the stamp should be included in calculating the Human score for the app. Useful when using a generic scoring schema.';



COMMENT ON COLUMN "public"."dapp_stamptypes"."is_infosharing_required" IS 'Defaults to false. Set to true if user is required to share their full info regarding a specific stamptype (e.g. phone number)';



ALTER TABLE "public"."dapp_stamptypes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_stamptypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_user_secrets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "dapp_user_uuid" "uuid" NOT NULL,
    "secret" "text" NOT NULL,
    "secret_sequential_id" bigint NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."dapp_user_secrets" OWNER TO "postgres";


ALTER TABLE "public"."dapp_user_secrets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_user_secrets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."dapp_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dapp_webhook_subscriptions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "webhook" "text" NOT NULL,
    "dapp" bigint NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "webhook_url" "text",
    "created_by_user" bigint,
    "secret" "text" NOT NULL
);


ALTER TABLE "public"."dapp_webhook_subscriptions" OWNER TO "postgres";


ALTER TABLE "public"."dapp_webhook_subscriptions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dapp_webhook_subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."email_otp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "otp" integer
);


ALTER TABLE "public"."email_otp" OWNER TO "postgres";


ALTER TABLE "public"."email_otp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."email_otp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."eth-api-accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "private_key" "text",
    "account_address" "text",
    "owner_id" bigint
);


ALTER TABLE "public"."eth-api-accounts" OWNER TO "postgres";


ALTER TABLE "public"."eth-api-accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."eth-api-accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."evm_accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "private_key" "text",
    "address" "text",
    "user_id" bigint,
    "dapp_id" bigint
);


ALTER TABLE "public"."evm_accounts" OWNER TO "postgres";


ALTER TABLE "public"."evm_accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evm_accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."cronjobs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."gitcoin_cronjob_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."info-sharing" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" character varying,
    "info_sharing_data" "jsonb"
);


ALTER TABLE "public"."info-sharing" OWNER TO "postgres";


ALTER TABLE "public"."info-sharing" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."info-sharing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."info_sharing_types" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Description" "text",
    "dropdown_description" "text",
    "prio" smallint,
    "isForPhone" boolean,
    "isForLocation" boolean,
    "isForGeneric" boolean
);


ALTER TABLE "public"."info_sharing_types" OWNER TO "postgres";


COMMENT ON COLUMN "public"."info_sharing_types"."dropdown_description" IS 'The text shown in the Admin Console UI';



COMMENT ON COLUMN "public"."info_sharing_types"."prio" IS 'Sorted most granular to least granular';



ALTER TABLE "public"."info_sharing_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."info_sharing_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ip_private_reveal" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sui_rec" bigint,
    "eth_rec" bigint,
    "near_rec" bigint,
    "ip" "text",
    "user_id" bigint
);


ALTER TABLE "public"."ip_private_reveal" OWNER TO "postgres";


ALTER TABLE "public"."ip_private_reveal" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ip_private_reveal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."near-api-accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_address" "text",
    "owner_id" bigint,
    "query_data" "jsonb",
    "private_key" "text"
);


ALTER TABLE "public"."near-api-accounts" OWNER TO "postgres";


ALTER TABLE "public"."near-api-accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."near-api-accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."postal_zip_codes" (
    "id" bigint NOT NULL,
    "postal_or_zip_code" "text",
    "lat" real,
    "lng" real,
    "country" "text" DEFAULT '''us''::text'::"text" NOT NULL
);


ALTER TABLE "public"."postal_zip_codes" OWNER TO "postgres";


COMMENT ON COLUMN "public"."postal_zip_codes"."country" IS 'Either postal code in Canada or zip code in the US';



ALTER TABLE "public"."postal_zip_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."postalcodes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."stamp_dappuser_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stamp_dappuser_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."stamptypes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stampcategories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."stamps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stamps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."stampscore_gp_equivalents" (
    "GP_equivalent" "text" NOT NULL,
    "GP_score" real NOT NULL
);


ALTER TABLE "public"."stampscore_gp_equivalents" OWNER TO "postgres";


COMMENT ON TABLE "public"."stampscore_gp_equivalents" IS 'One place to manage the equivalent stamp scores in Gitcoin Passport';



ALTER TABLE "public"."stampscore_schemas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stampscore_schemas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."stampscores_available" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stampscores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "active_subscription_name" "text",
    "is_lifetime" boolean,
    "email" "text"
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


ALTER TABLE "public"."subscriptions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."suggested-todos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "text" "text",
    "priority_level" bigint
);


ALTER TABLE "public"."suggested-todos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sui-api-accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_address" "text",
    "private_key" "text",
    "owner_id" bigint
);


ALTER TABLE "public"."sui-api-accounts" OWNER TO "postgres";


ALTER TABLE "public"."sui-api-accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sui-api-accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "category" "text",
    "action_name" "text",
    "priority" bigint,
    "target repo" "text",
    "started" "jsonb",
    "completed" "jsonb",
    "sibling" "jsonb"
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


ALTER TABLE "public"."suggested-todos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."todos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."todos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."todos_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "transaction_data" json,
    "amount" double precision,
    "transaction_type" "text",
    "email" "text"
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."uniquestamps" (
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "stamptype" smallint NOT NULL,
    "uniquehash" "text" NOT NULL,
    "blacklisted" boolean DEFAULT false,
    "unencrypted_unique_data" "text",
    "created_by_user_id" bigint,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "type_and_hash" "text" NOT NULL,
    "created_by_app_id" smallint[],
    "is_singleuser" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."uniquestamps" OWNER TO "postgres";


COMMENT ON TABLE "public"."uniquestamps" IS 'Each combination of uniquevalue and stamptype can only exist once. If more than one top level user is detected, then the combination is blacklisted.';



COMMENT ON COLUMN "public"."uniquestamps"."stamptype" IS 'Each stamp must have a type from the stamptypes table';



COMMENT ON COLUMN "public"."uniquestamps"."uniquehash" IS 'This is a hash of the uniquedata in the stamps table';



COMMENT ON COLUMN "public"."uniquestamps"."blacklisted" IS 'Deprecated, replaced by is_singleuser';



COMMENT ON COLUMN "public"."uniquestamps"."created_by_user_id" IS 'This column only shows which user FIRST created the stamp. It has no real purpose other than as an FYI audit log for testing. Should not be used for logic.';



COMMENT ON COLUMN "public"."uniquestamps"."type_and_hash" IS 'Concatenating the two to make a foreign key for the stamps';



COMMENT ON COLUMN "public"."uniquestamps"."is_singleuser" IS 'Originally called "Blacklist", this bool is defaults to true and is switched to false whenever we detect that more than one user has been using or has shown us that they are in control of the same uniquevalue (email, phone, social account, etc.) as another user.';



ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."voting_list" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "month" "text",
    "description" "text",
    "hours_claimed" integer,
    "email" "text",
    "people_you_worked_with" "jsonb",
    "paid" boolean,
    "hour_details" "jsonb",
    "name" "text"
);


ALTER TABLE "public"."voting_list" OWNER TO "postgres";


ALTER TABLE "public"."voting_list" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."voting_list_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallet_details" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "seedphrase" "text",
    "wallet-address" "text",
    "email" "text",
    "wallet_data" "jsonb",
    "unique_phone" "text"
);


ALTER TABLE "public"."wallet_details" OWNER TO "postgres";


ALTER TABLE "public"."wallet_details" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallet_details_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallet_list" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "public_key" "text" NOT NULL,
    "chain" "text",
    "dapp_user" "uuid",
    "is_generated_via_lib" boolean DEFAULT false
);


ALTER TABLE "public"."wallet_list" OWNER TO "postgres";


ALTER TABLE "public"."wallet_list" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallet_list_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhook_event_deliveries" (
    "id" bigint NOT NULL,
    "webhook_event_id" bigint NOT NULL,
    "dapp_id" bigint NOT NULL,
    "attempt_number" integer DEFAULT 0 NOT NULL,
    "response_status_code" integer,
    "response_body" "text",
    "error_category" "public"."error_category",
    "delivered_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "delivery_status" "public"."delivery_status",
    "last_attempt_at" timestamp without time zone,
    "is_queued_and_active" boolean,
    "is_resulted_in_subscription_disabled" boolean
);


ALTER TABLE "public"."webhook_event_deliveries" OWNER TO "postgres";


ALTER TABLE "public"."webhook_event_deliveries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhook_event_deliveries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhook_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_type" "text" NOT NULL,
    "payload" "jsonb" NOT NULL,
    "retries" integer DEFAULT 0 NOT NULL,
    "last_attempt_at" timestamp with time zone,
    "dapp_id" bigint
);


ALTER TABLE "public"."webhook_events" OWNER TO "postgres";


COMMENT ON TABLE "public"."webhook_events" IS 'This table stores all generated webhook events, their payloads, and status - across all dapps.';



ALTER TABLE "public"."webhook_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhook_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhook_types" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "action_type" "text"
);


ALTER TABLE "public"."webhook_types" OWNER TO "postgres";


ALTER TABLE "public"."webhook_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."whitelist" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "identifier" "text"
);


ALTER TABLE "public"."whitelist" OWNER TO "postgres";


ALTER TABLE "public"."whitelist" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."whitelist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."dapp-admin-users"
    ADD CONSTRAINT "admin-users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."dapp-admin-users"
    ADD CONSTRAINT "admin-users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."authorized_dapps_deprecated"
    ADD CONSTRAINT "authorized_dapps_dapp_and_stamp_id_key" UNIQUE ("dapp_and_stamp_id");



ALTER TABLE ONLY "public"."authorized_dapps_deprecated"
    ADD CONSTRAINT "authorized_dapps_pkey" PRIMARY KEY ("dapp_id", "stamp_id");



ALTER TABLE ONLY "public"."blacklist_deprecated"
    ADD CONSTRAINT "blacklist_identifier_key" UNIQUE ("identifier");



ALTER TABLE ONLY "public"."blacklist_deprecated"
    ADD CONSTRAINT "blacklist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."brightid-data"
    ADD CONSTRAINT "brightid-data_both-id_key" UNIQUE ("both-id");



ALTER TABLE ONLY "public"."brightid-data"
    ADD CONSTRAINT "brightid-data_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."connections"
    ADD CONSTRAINT "connections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cron_logs"
    ADD CONSTRAINT "cron_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dapps"
    ADD CONSTRAINT "cubid-superapps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dapp_pages"
    ADD CONSTRAINT "dapp_pages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dapp_stampscores_deprecated"
    ADD CONSTRAINT "dapp_stampscores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dapp_stamptypes"
    ADD CONSTRAINT "dapp_stamptypes_pkey" PRIMARY KEY ("stamptype_id", "page_id");



ALTER TABLE ONLY "public"."dapp_user_secrets"
    ADD CONSTRAINT "dapp_user_secrets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "dapp_users_UUID_key" UNIQUE ("uuid");



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "dapp_users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "dapp_users_pkey" PRIMARY KEY ("dapp_id", "user_id");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_pkey" PRIMARY KEY ("webhook", "dapp");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_secret_key" UNIQUE ("secret");



ALTER TABLE ONLY "public"."dapps"
    ADD CONSTRAINT "dapps_apikey_key" UNIQUE ("apikey");



ALTER TABLE ONLY "public"."dapps"
    ADD CONSTRAINT "dapps_uid_key" UNIQUE ("uid");



ALTER TABLE ONLY "public"."email_otp"
    ADD CONSTRAINT "email_otp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."eth-api-accounts"
    ADD CONSTRAINT "eth-api-accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evm_accounts"
    ADD CONSTRAINT "evm_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cronjobs"
    ADD CONSTRAINT "gitcoin_cronjob_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."info-sharing"
    ADD CONSTRAINT "info-sharing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."info_sharing_types"
    ADD CONSTRAINT "info_sharing_types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ip_private_reveal"
    ADD CONSTRAINT "ip_private_reveal_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."near-api-accounts"
    ADD CONSTRAINT "near-api-accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."postal_zip_codes"
    ADD CONSTRAINT "postalcodes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stamp_dappuser_permissions"
    ADD CONSTRAINT "stamp_dappuser_permissions_pkey" PRIMARY KEY ("dappuser_id", "stamp_id");



ALTER TABLE ONLY "public"."stamptypes"
    ADD CONSTRAINT "stampcategories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "stamps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stampscore_dapps"
    ADD CONSTRAINT "stampscore_dapps_pkey" PRIMARY KEY ("API_key", "dapp_id", "schema_id");



ALTER TABLE ONLY "public"."stampscore_gp_equivalents"
    ADD CONSTRAINT "stampscore_gp_equivalents_pkey" PRIMARY KEY ("GP_equivalent");



ALTER TABLE ONLY "public"."stampscore_schemas"
    ADD CONSTRAINT "stampscore_schemas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stampscores_available"
    ADD CONSTRAINT "stampscores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sui-api-accounts"
    ADD CONSTRAINT "sui-api-accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."suggested-todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "unique_auth_value_stamptype" UNIQUE ("is_auth", "uniquevalue", "stamptype");



ALTER TABLE ONLY "public"."webhook_event_deliveries"
    ADD CONSTRAINT "unique_delivery_attempt" UNIQUE ("webhook_event_id", "dapp_id");



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "unique_stamps_constraint" UNIQUE ("created_by_user_id", "created_by_app", "uniquevalue", "stamptype");



ALTER TABLE ONLY "public"."uniquestamps"
    ADD CONSTRAINT "uniquestamps_created_by_app_id_key" UNIQUE ("created_by_app_id");



ALTER TABLE ONLY "public"."uniquestamps"
    ADD CONSTRAINT "uniquestamps_type_and_hash_key" UNIQUE ("type_and_hash");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_evm_key" UNIQUE ("evm");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_phone_key" UNIQUE ("phone");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_unique_phone_key" UNIQUE ("unique_phone");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."voting_list"
    ADD CONSTRAINT "voting_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallet_details"
    ADD CONSTRAINT "wallet_details_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallet_list"
    ADD CONSTRAINT "wallet_list_dapp_user_key" UNIQUE ("dapp_user");



ALTER TABLE ONLY "public"."wallet_list"
    ADD CONSTRAINT "wallet_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."wallet_list"
    ADD CONSTRAINT "wallet_list_public_key_key" UNIQUE ("public_key");



ALTER TABLE ONLY "public"."webhook_event_deliveries"
    ADD CONSTRAINT "webhook_event_deliveries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhook_events"
    ADD CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhook_types"
    ADD CONSTRAINT "webhooks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."webhook_types"
    ADD CONSTRAINT "webhooks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."whitelist"
    ADD CONSTRAINT "whitelist_identifier_key" UNIQUE ("identifier");



ALTER TABLE ONLY "public"."whitelist"
    ADD CONSTRAINT "whitelist_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "trigger_assign_secret_number" BEFORE INSERT ON "public"."dapp_user_secrets" FOR EACH ROW EXECUTE FUNCTION "public"."assign_secret_number"();



ALTER TABLE ONLY "public"."authorized_dapps_deprecated"
    ADD CONSTRAINT "authorized_dapps_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."authorized_dapps_deprecated"
    ADD CONSTRAINT "authorized_dapps_stamp_id_fkey" FOREIGN KEY ("stamp_id") REFERENCES "public"."stamps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."connections"
    ADD CONSTRAINT "connections_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."connections"
    ADD CONSTRAINT "connections_target_user_id_fkey" FOREIGN KEY ("target_user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."cronjobs"
    ADD CONSTRAINT "cronjobs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_pages"
    ADD CONSTRAINT "dapp_pages_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_stamptypes"
    ADD CONSTRAINT "dapp_stamptypes_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."dapp_pages"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_user_secrets"
    ADD CONSTRAINT "dapp_user_secrets_dapp_user_uuid_fkey" FOREIGN KEY ("dapp_user_uuid") REFERENCES "public"."dapp_users"("uuid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "dapp_users_auth_stamp_fkey" FOREIGN KEY ("auth_stamp") REFERENCES "public"."stamps"("id");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_created_by_user_fkey" FOREIGN KEY ("created_by_user") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_dapp_fkey" FOREIGN KEY ("dapp") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."dapp_webhook_subscriptions"
    ADD CONSTRAINT "dapp_webhook_subscriptions_webhook_fkey" FOREIGN KEY ("webhook") REFERENCES "public"."webhook_types"("name") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eth-api-accounts"
    ADD CONSTRAINT "eth-api-accounts_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."evm_accounts"
    ADD CONSTRAINT "evm_accounts_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."ip_private_reveal"
    ADD CONSTRAINT "ip_private_reveal_eth_rec_fkey" FOREIGN KEY ("eth_rec") REFERENCES "public"."eth-api-accounts"("id");



ALTER TABLE ONLY "public"."ip_private_reveal"
    ADD CONSTRAINT "ip_private_reveal_near_rec_fkey" FOREIGN KEY ("near_rec") REFERENCES "public"."near-api-accounts"("id");



ALTER TABLE ONLY "public"."ip_private_reveal"
    ADD CONSTRAINT "ip_private_reveal_sui_rec_fkey" FOREIGN KEY ("sui_rec") REFERENCES "public"."sui-api-accounts"("id");



ALTER TABLE ONLY "public"."ip_private_reveal"
    ADD CONSTRAINT "ip_private_reveal_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."near-api-accounts"
    ADD CONSTRAINT "near-api-accounts_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."dapp-admin-users"
    ADD CONSTRAINT "public_dapp-admin-users_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp-admin-users"
    ADD CONSTRAINT "public_dapp-admin-users_dappuser_id_fkey" FOREIGN KEY ("dappuser_uuid") REFERENCES "public"."dapp_users"("uuid");



ALTER TABLE ONLY "public"."dapp_stampscores_deprecated"
    ADD CONSTRAINT "public_dapp_stampscores_stamptype_id_fkey" FOREIGN KEY ("stamptype_id") REFERENCES "public"."stamptypes"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."dapp_stamptypes"
    ADD CONSTRAINT "public_dapp_stamptypes_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_stamptypes"
    ADD CONSTRAINT "public_dapp_stamptypes_info_sharing_type_fkey" FOREIGN KEY ("info_sharing_type_id") REFERENCES "public"."info_sharing_types"("id");



ALTER TABLE ONLY "public"."dapp_stamptypes"
    ADD CONSTRAINT "public_dapp_stamptypes_stamptype_id_fkey" FOREIGN KEY ("stamptype_id") REFERENCES "public"."stamptypes"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "public_dapp_users_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dapp_users"
    ADD CONSTRAINT "public_dapp_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."stamp_dappuser_permissions"
    ADD CONSTRAINT "public_stamp_dappuser_permissions_dappuser_id_fkey" FOREIGN KEY ("dappuser_id") REFERENCES "public"."dapp_users"("uuid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stamp_dappuser_permissions"
    ADD CONSTRAINT "public_stamp_dappuser_permissions_stamp_id_fkey" FOREIGN KEY ("stamp_id") REFERENCES "public"."stamps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stampscore_dapps"
    ADD CONSTRAINT "public_stampscore_dapps_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stampscore_dapps"
    ADD CONSTRAINT "public_stampscore_dapps_schema_id_fkey" FOREIGN KEY ("schema_id") REFERENCES "public"."stampscore_schemas"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stampscores_available"
    ADD CONSTRAINT "public_stampscores_available_GP2_fkey" FOREIGN KEY ("GP_equivalent") REFERENCES "public"."stampscore_gp_equivalents"("GP_equivalent");



ALTER TABLE ONLY "public"."stampscores_available"
    ADD CONSTRAINT "public_stampscores_schema_id_fkey" FOREIGN KEY ("schema_id") REFERENCES "public"."stampscore_schemas"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stampscores_available"
    ADD CONSTRAINT "public_stampscores_stamptype_id_fkey" FOREIGN KEY ("stamptype_id") REFERENCES "public"."stamptypes"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "stamps_created_by_app_fkey" FOREIGN KEY ("created_by_app") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "stamps_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "stamps_parent_stamp_fkey" FOREIGN KEY ("parent_stamp") REFERENCES "public"."stamps"("id");



ALTER TABLE ONLY "public"."stamps"
    ADD CONSTRAINT "stamps_stamptype_fkey" FOREIGN KEY ("stamptype") REFERENCES "public"."stamptypes"("id");



ALTER TABLE ONLY "public"."sui-api-accounts"
    ADD CONSTRAINT "sui-api-accounts_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."uniquestamps"
    ADD CONSTRAINT "uniquestamps_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."uniquestamps"
    ADD CONSTRAINT "uniquestamps_stamptype_fkey" FOREIGN KEY ("stamptype") REFERENCES "public"."stamptypes"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_created_by_app_fkey" FOREIGN KEY ("created_by_app") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_parent_fkey" FOREIGN KEY ("parent") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."wallet_list"
    ADD CONSTRAINT "wallet_list_dapp_user_fkey" FOREIGN KEY ("dapp_user") REFERENCES "public"."dapp_users"("uuid");



ALTER TABLE ONLY "public"."webhook_event_deliveries"
    ADD CONSTRAINT "webhook_event_deliveries_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."webhook_event_deliveries"
    ADD CONSTRAINT "webhook_event_deliveries_webhook_event_id_fkey" FOREIGN KEY ("webhook_event_id") REFERENCES "public"."webhook_events"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."webhook_events"
    ADD CONSTRAINT "webhook_events_dapp_id_fkey" FOREIGN KEY ("dapp_id") REFERENCES "public"."dapps"("id");



ALTER TABLE ONLY "public"."webhook_events"
    ADD CONSTRAINT "webhook_events_event_type_fkey" FOREIGN KEY ("event_type") REFERENCES "public"."webhook_types"("name") ON UPDATE CASCADE;



CREATE POLICY "Service role only" ON "public"."users" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Allow inserts from service role" ON "public"."cron_logs" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."dapp_stampscores_deprecated" FOR SELECT USING (true);



CREATE POLICY "Policy with security definer functions" ON "public"."dapps" USING (true);



ALTER TABLE "public"."authorized_dapps_deprecated" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blacklist_deprecated" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."brightid-data" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."connections" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cron_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cronjobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp-admin-users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_pages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_stampscores_deprecated" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_stamptypes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_user_secrets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapp_webhook_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dapps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."email_otp" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."eth-api-accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."evm_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."info-sharing" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."info_sharing_types" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ip_private_reveal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."near-api-accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."postal_zip_codes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stamp_dappuser_permissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stamps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stampscore_dapps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stampscore_gp_equivalents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stampscore_schemas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stampscores_available" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stamptypes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."suggested-todos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sui-api-accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."uniquestamps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."voting_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."wallet_details" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."wallet_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhook_event_deliveries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhook_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhook_types" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."whitelist" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT USAGE ON SCHEMA "public" TO "postgres";































































































































































GRANT ALL ON FUNCTION "public"."assign_secret_number"() TO "anon";
GRANT ALL ON FUNCTION "public"."assign_secret_number"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."assign_secret_number"() TO "service_role";



GRANT ALL ON FUNCTION "public"."create_user_check_family"("p_uniquevalue" "text", "p_stamptype" smallint, "p_dapp_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."create_user_check_family"("p_uniquevalue" "text", "p_stamptype" smallint, "p_dapp_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_user_check_family"("p_uniquevalue" "text", "p_stamptype" smallint, "p_dapp_id" bigint) TO "service_role";
























GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp-admin-users" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp-admin-users" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp-admin-users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admin-users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admin-users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admin-users_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_users" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_users" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_users" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_hashed" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_hashed" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_hashed" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_raw" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_raw" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_blacklisted_stamps_raw" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamp_dappuser_permissions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamp_dappuser_permissions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamp_dappuser_permissions" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_dapps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_dapps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_dapps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscores_available" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscores_available" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscores_available" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_user" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_user" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_dappusers_w_user" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_users_and_parents" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_users_and_parents" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_users_and_parents" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_duplicate_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_duplicate_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_duplicate_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps_raw" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps_raw" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_greylisted_stamps_raw" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamp_identities" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamp_identities" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamp_identities" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_whitelisted_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_whitelisted_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_whitelisted_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamptypes" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamptypes" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stamptypes" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stamps" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_schemas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_schemas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_schemas" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stampscores_available_extended" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stampscores_available_extended" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_stampscores_available_extended" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_detailed" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_detailed" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_detailed" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_expanded" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_expanded" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."all_unique_stamps_expanded" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."authorized_dapps_deprecated" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."authorized_dapps_deprecated" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."authorized_dapps_deprecated" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."blacklist_deprecated" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."blacklist_deprecated" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."blacklist_deprecated" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."brightid-data" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."brightid-data" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."brightid-data" TO "service_role";



GRANT ALL ON SEQUENCE "public"."brightid-data_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."brightid-data_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."brightid-data_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."connections" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."connections" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."connections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."connections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."connections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."connections_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cron_logs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cron_logs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cron_logs" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cronjobs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cronjobs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."cronjobs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cubid-superapps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cubid-superapps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cubid-superapps_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_pages" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_pages" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_pages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_pages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_pages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_pages_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stampscores_deprecated" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stampscores_deprecated" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stampscores_deprecated" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_stampscores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_stampscores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_stampscores_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stamptypes" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stamptypes" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_stamptypes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_stamptypes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_stamptypes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_stamptypes_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_user_secrets" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_user_secrets" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_user_secrets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_user_secrets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_user_secrets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_user_secrets_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_users_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_webhook_subscriptions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_webhook_subscriptions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."dapp_webhook_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dapp_webhook_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dapp_webhook_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dapp_webhook_subscriptions_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."email_otp" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."email_otp" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."email_otp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."email_otp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."email_otp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."email_otp_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."eth-api-accounts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."eth-api-accounts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."eth-api-accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."eth-api-accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."eth-api-accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."eth-api-accounts_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evm_accounts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evm_accounts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evm_accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."evm_accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evm_accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evm_accounts_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."gitcoin_cronjob_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."gitcoin_cronjob_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."gitcoin_cronjob_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info-sharing" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info-sharing" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info-sharing" TO "service_role";



GRANT ALL ON SEQUENCE "public"."info-sharing_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."info-sharing_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."info-sharing_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info_sharing_types" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info_sharing_types" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."info_sharing_types" TO "service_role";



GRANT ALL ON SEQUENCE "public"."info_sharing_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."info_sharing_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."info_sharing_types_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ip_private_reveal" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ip_private_reveal" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ip_private_reveal" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ip_private_reveal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ip_private_reveal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ip_private_reveal_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."near-api-accounts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."near-api-accounts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."near-api-accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."near-api-accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."near-api-accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."near-api-accounts_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."postal_zip_codes" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."postal_zip_codes" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."postal_zip_codes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."postalcodes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."postalcodes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."postalcodes_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stamp_dappuser_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stamp_dappuser_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stamp_dappuser_permissions_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stampcategories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stampcategories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stampcategories_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stamps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stamps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stamps_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_gp_equivalents" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_gp_equivalents" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."stampscore_gp_equivalents" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stampscore_schemas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stampscore_schemas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stampscore_schemas_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stampscores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stampscores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stampscores_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."suggested-todos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."suggested-todos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."suggested-todos" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sui-api-accounts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sui-api-accounts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sui-api-accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sui-api-accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sui-api-accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sui-api-accounts_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."todos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."todos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."todos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."todos_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."todos_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."todos_id_seq1" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."transactions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."transactions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."uniquestamps" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."uniquestamps" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."uniquestamps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."voting_list" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."voting_list" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."voting_list" TO "service_role";



GRANT ALL ON SEQUENCE "public"."voting_list_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."voting_list_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."voting_list_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_details" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_details" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_details" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallet_details_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallet_details_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallet_details_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_list" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_list" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."wallet_list" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallet_list_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallet_list_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallet_list_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_event_deliveries" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_event_deliveries" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_event_deliveries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhook_event_deliveries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhook_event_deliveries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhook_event_deliveries_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_events" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_events" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_types" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_types" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."webhook_types" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhooks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhooks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhooks_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."whitelist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."whitelist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."whitelist_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































drop extension if exists "pg_net";

