create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;
grant usage on schema private to service_role;

create table if not exists private.dapp_user_secrets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  dapp_user_uuid uuid not null references public.dapp_users(uuid) on delete cascade,
  secret text not null default '__cubid_encrypted_dapp_user_secret__',
  secret_sequential_id bigint not null,
  description text,
  legacy_public_secret_id bigint,
  secret_ciphertext text not null,
  secret_iv text not null,
  secret_auth_tag text not null,
  wrapped_data_key text not null,
  wrapped_data_key_iv text not null,
  wrapped_data_key_auth_tag text not null,
  encryption_algorithm text not null,
  encryption_key_id text not null,
  encryption_key_version integer not null,
  encryption_purpose text not null,
  encryption_context jsonb not null default '{}'::jsonb,
  encrypted_at timestamptz not null default now(),
  migrated_from_public_at timestamptz,
  constraint private_dapp_user_secrets_algorithm_check
    check (encryption_algorithm = 'aes-256-gcm-envelope'),
  constraint private_dapp_user_secrets_key_version_check
    check (encryption_key_version > 0)
);

create index if not exists private_dapp_user_secrets_dapp_user_uuid_idx
  on private.dapp_user_secrets(dapp_user_uuid);

create unique index if not exists private_dapp_user_secrets_dapp_user_sequence_idx
  on private.dapp_user_secrets(dapp_user_uuid, secret_sequential_id);

create unique index if not exists private_dapp_user_secrets_legacy_public_id_idx
  on private.dapp_user_secrets(legacy_public_secret_id)
  where legacy_public_secret_id is not null;

alter table private.dapp_user_secrets enable row level security;

revoke all on table private.dapp_user_secrets from public;
revoke all on table private.dapp_user_secrets from anon;
revoke all on table private.dapp_user_secrets from authenticated;
grant select, insert, update, delete on table private.dapp_user_secrets to service_role;
grant usage, select on sequence private.dapp_user_secrets_id_seq to service_role;

create or replace function public.get_dapp_user_secret_wrapping_key_v1()
returns text
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare
  secret_value text;
begin
  select decrypted_secret
    into secret_value
    from vault.decrypted_secrets
   where name = 'passport_dapp_user_secret_wrapping_key_v1'
   limit 1;

  if secret_value is null or length(secret_value) < 43 then
    raise exception 'passport_dapp_user_secret_wrapping_key_v1 is missing from Supabase Vault'
      using errcode = '22023';
  end if;

  return secret_value;
end;
$$;

revoke all on function public.get_dapp_user_secret_wrapping_key_v1() from public;
grant execute on function public.get_dapp_user_secret_wrapping_key_v1() to service_role;
